# Generated by Django 5.1.3 on 2025-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
